version: '3.7'

services:
  naming-server:
    image: pollitodev/microservice-example-naming-server:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
      - "8761:8761"
    networks:
      - pollito-mocroservice-example-network

  api-gateway:
    image: pollitodev/microservice-example-api-gateway:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
      - "8765:8765"
    networks:
      - pollito-mocroservice-example-network
    depends_on:
      - naming-server
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE:  http://naming-server:8761/eureka

  microservice-a:
    image: pollitodev/microservice-example-microservice-a:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
      - "8100:8100"
    networks:
      - pollito-mocroservice-example-network
    depends_on:
      - naming-server
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE:  http://naming-server:8761/eureka
      MICROSERVICE-B.BASEURL:  http://api-gateway:8765/microservice-b

  microservice-b:
    image: pollitodev/microservice-example-microservice-b:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
      - "8000:8000"
    networks:
      - pollito-mocroservice-example-network
    depends_on:
      - naming-server
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE:  http://naming-server:8761/eureka

networks:
  pollito-mocroservice-example-network: